# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies and build the project
COPY package.json tsconfig.json ./
COPY src ./src

RUN apk add --no-cache python3 make g++ \
    && npm install --ignore-scripts \
    && npm run build \
    && apk del python3 make g++

# Default command runs the MCP server over stdio
CMD ["node", "build/cli.js"]
